2018-09-22 19:14:38 [ INFO ] [ DubboProtocol$1.java :122(disconnected)]   [DUBBO] disconected from /192.168.0.108:20881,url:dubbo://192.168.0.108:20881/com.zheng.upms.rpc.api.UpmsApiService?anyhost=true&application=tmsp-server&check=false&codec=dubbo&default.check=false&dubbo=2.5.6&generic=false&heartbeat=60000&interface=com.zheng.upms.rpc.api.UpmsApiService&methods=selectUpmsOrganizationByExample,insertUpmsLogSelective,selectUpmsRoleByUpmsUserId,selectUpmsRolePermisstionByUpmsRoleId,selectUpmsSystemByExample,selectUpmsPermissionByUpmsUserIdByCache,selectUpmsUserByUsername,selectUpmsRoleByUpmsUserIdByCache,selectUpmsPermissionByUpmsUserId,selectUpmsUserPermissionByUpmsUserId&mock=true&pid=11232&remote.timestamp=1537521987040&revision=1.0.0&side=consumer&timeout=10000&timestamp=1537522033469, dubbo version: 2.5.6, current host: 192.168.0.108
2018-09-22 19:14:40 [ WARN ] [ AbstractClient$1.java :172(run)]   [DUBBO] client reconnect to 192.168.0.108:20881 find error . url: dubbo://192.168.0.108:20881/com.zheng.upms.rpc.api.UpmsApiService?anyhost=true&application=tmsp-server&check=false&codec=dubbo&default.check=false&dubbo=2.5.6&generic=false&heartbeat=60000&interface=com.zheng.upms.rpc.api.UpmsApiService&methods=selectUpmsOrganizationByExample,insertUpmsLogSelective,selectUpmsRoleByUpmsUserId,selectUpmsRolePermisstionByUpmsRoleId,selectUpmsSystemByExample,selectUpmsPermissionByUpmsUserIdByCache,selectUpmsUserByUsername,selectUpmsRoleByUpmsUserIdByCache,selectUpmsPermissionByUpmsUserId,selectUpmsUserPermissionByUpmsUserId&mock=true&pid=11232&remote.timestamp=1537521987040&revision=1.0.0&side=consumer&timeout=10000&timestamp=1537522033469, dubbo version: 2.5.6, current host: 192.168.0.108
com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://192.168.0.108:20881/com.zheng.upms.rpc.api.UpmsApiService?anyhost=true&application=tmsp-server&check=false&codec=dubbo&default.check=false&dubbo=2.5.6&generic=false&heartbeat=60000&interface=com.zheng.upms.rpc.api.UpmsApiService&methods=selectUpmsOrganizationByExample,insertUpmsLogSelective,selectUpmsRoleByUpmsUserId,selectUpmsRolePermisstionByUpmsRoleId,selectUpmsSystemByExample,selectUpmsPermissionByUpmsUserIdByCache,selectUpmsUserByUsername,selectUpmsRoleByUpmsUserIdByCache,selectUpmsPermissionByUpmsUserId,selectUpmsUserPermissionByUpmsUserId&mock=true&pid=11232&remote.timestamp=1537521987040&revision=1.0.0&side=consumer&timeout=10000&timestamp=1537522033469) failed to connect to server /192.168.0.108:20881, error message is:Connection refused: no further information
	at com.alibaba.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:124)
	at com.alibaba.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:268)
	at com.alibaba.dubbo.remoting.transport.AbstractClient$1.run(AbstractClient.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:384)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276)
	... 3 more
